### ISSUE TITLE
The Set length tests the array rather than the Set

### ISSUE THREAD

**Issue by orbanbotond** [eventide-project/collection#12]
An Array is instantiated in the test code testing the `Set`:
```
 context "Set" do
   context "Length" do
-    collection = Collection::Array.new(String)
```
https://github.com/eventide-project/collection/blob/3bd56337b68d7dc8002bfc8d8062a1a3d8cf4e45/test/automated/set/length.rb#L5

The PR for instantiating it right is here:
https://github.com/eventide-project/collection/pulls

**Comment by ntl** [comment]
Closing (see comment on issue #11)
